"""moddifyy

Revision ID: b22e988d6195
Revises: 2b7f0a7e1c2d
Create Date: 2026-05-13 21:24:59.993043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22e988d6195'
down_revision: Union[str, None] = '2b7f0a7e1c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Normalize token_expires_at to naive UTC timestamp (matches TIMESTAMP WITHOUT TIME ZONE)
    op.execute("SET TIME ZONE 'UTC'")
    op.execute(
        """
        UPDATE users
        SET token_expires_at = token_expires_at::timestamp
        WHERE token_expires_at IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE users
        SET created_at = created_at::timestamp
        WHERE created_at IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE animals
        SET created_at = created_at::timestamp
        WHERE created_at IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE animals
        SET updated_at = updated_at::timestamp
        WHERE updated_at IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE financial
        SET created_at = created_at::timestamp
        WHERE created_at IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE system_logs
        SET created_at = created_at::timestamp
        WHERE created_at IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE vaccines
        SET created_at = created_at::timestamp
        WHERE created_at IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE inventory_items
        SET created_at = created_at::timestamp
        WHERE created_at IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE inventory_items
        SET updated_at = updated_at::timestamp
        WHERE updated_at IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE inventory_movements
        SET created_at = created_at::timestamp
        WHERE created_at IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE donations
        SET created_at = created_at::timestamp
        WHERE created_at IS NOT NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op: we do not re-apply timezone information once normalized.
    # ### end Alembic commands ###
    pass