"""Update column

Revision ID: bfab21f5afed
Revises: bbbb1222f5e1
Create Date: 2026-04-11 13:32:57.369048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfab21f5afed'
down_revision: Union[str, None] = 'bbbb1222f5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('estimated_age', sa.Float(), nullable=False))
    op.add_column('dogs', sa.Column('neutered', sa.Boolean(), nullable=False))
    op.add_column('dogs', sa.Column('dewormed', sa.Boolean(), nullable=False))
    op.add_column('dogs', sa.Column('socializes_with_other_dogs', sa.Boolean(), nullable=False))
    op.add_column('dogs', sa.Column('color', sa.String(length=50), nullable=True))
    op.drop_column('dogs', 'estimated_age_months')
    op.alter_column('vaccines', 'next_dose',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccines', 'next_dose',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('dogs', sa.Column('estimated_age_months', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('dogs', 'color')
    op.drop_column('dogs', 'socializes_with_other_dogs')
    op.drop_column('dogs', 'dewormed')
    op.drop_column('dogs', 'neutered')
    op.drop_column('dogs', 'estimated_age')
    # ### end Alembic commands ###
