"""user admin

Revision ID: eba5f264a5a5
Revises: 35e5aa096dae
Create Date: 2026-05-06 20:14:49.981007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba5f264a5a5'
down_revision: Union[str, None] = '35e5aa096dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from datetime import datetime, timezone
    import bcrypt

    bind = op.get_bind()
    hashed = bcrypt.hashpw(b"Admin@abrigo2025", bcrypt.gensalt()).decode("utf-8")

    bind.execute(sa.text("""
        INSERT INTO permissions (name, description)
        VALUES ('manage_all', 'Acesso total e irrestrito ao sistema')
        ON CONFLICT (name) DO NOTHING
    """))

    bind.execute(sa.text("""
        INSERT INTO roles (name)
        VALUES ('admin')
        ON CONFLICT (name) DO NOTHING
    """))

    role_id = bind.execute(
        sa.text("SELECT id FROM roles WHERE name = 'admin'")
    ).scalar()

    permission_id = bind.execute(
        sa.text("SELECT id FROM permissions WHERE name = 'manage_all'")
    ).scalar()

    if role_id and permission_id:
        bind.execute(
            sa.text("""
                INSERT INTO role_permissions (role_id, permission_id)
                VALUES (:role_id, :permission_id)
                ON CONFLICT DO NOTHING
            """)
            .bindparams(role_id=role_id, permission_id=permission_id)
        )

    if role_id:
        bind.execute(
            sa.text(
                """
                INSERT INTO users (full_name, email, hashed_password, is_active, role_id, created_at)
                VALUES (:full_name, :email, :hashed_password, :is_active, :role_id, :created_at)
                ON CONFLICT (email) DO NOTHING
                """
            ).bindparams(
                full_name="Administrador",
                email="admin@abrigo.com",
                hashed_password=hashed,
                is_active=True,
                role_id=role_id,
                created_at=datetime.now(timezone.utc),
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("DELETE FROM users WHERE email = 'admin@abrigo.com'")
    )
    # ### end Alembic commands ###
