name: abrigo-caes

services:
  api:
    build: .
    restart: unless-stopped
    env_file: .env
    command: >
      sh -c "sleep 10 &&
             alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port ${PORT}"

  db:
    image: mysql:9.4.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
